language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"


install:
    - python setup.py -q install

script:
    - for path in "$(find src/ -type f -wholename '*/test/test*'.py)";do python $path || exit 1; done;

notifications:
    email: false
