language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"


install:
    - python setup.py -q install

script:
    - python src/pymfony/component/system/test/test_system.py
    - python src/pymfony/component/kernel/test/test_functional.py
    - python src/pymfony/component/dispatcher/test/test_EventDispatcher.py

notifications:
    email: false
