language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
# command to install dependencies
install:
    - python setup.py -q install
# command to run tests
script:
    - python src/pymfony/component/kernel/tests/test_system.py
    - python src/pymfony/component/kernel/tests/functional/test_functional.py
