language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"


install:
    - python setup.py -q install

script:
    - find src/ -type f -wholename */test/test*.py -exec python {} \;

notifications:
    email: false
